# Generated by Django 5.2.17 on 2026-09-20 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblemScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_attempts', models.PositiveIntegerField(default=0)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('first_ac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='judge.submission')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'problem'], name='ranking_use_user_id_2febbe_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'problem'), name='uniq_user_problem_score')],
            },
        ),
    ]
